---
title: "Análisis ENADEL 2023 <br> Reporte"
subtitle: 
  - "        ACNUR"
author: "Cliodinámica"
date: "`r Sys.Date()`"
output: 
  html_document:
    css: style.css
    toc: true
    toc-title: "Índice"
---


<style>
  p {
    text-align: justify;
  }
</style>


Ministerio del Trabajo y Previsión Social


División de Políticas de Empleo
Subsecretaría del Trabajo




El presente documento analiza los resultados de la Encuesta Nacional de Demanda Laboral (ENADEL) 2023, que busca identificar y caracterizar el capital humano requerido por las empresas de los distintos sectores productivos del país, generando información sobre la demanda actual de ocupaciones de las empresas, detectando requisitos y problemas de contratación. Al igual que versiones anteriores de esta encuesta, se puso el foco en dos sectores de actividad económica: Construcción y el sector Agrícola.


---
### Descripción General: Empresas y Trabajadores

La muestra de ENADEL 2023 encuesta a 5.820 empresas que suman 485.256 trabajadores (a nivel muestral). Estas representan a 82.052 empresas y 5.611.196 trabajadores a nivel nacional.
La Tabla 1 muestra la distribución en las distintas regiones del país, dónde un 53,6% de las empresas y un 65,6% de los trabajadores se encuentran en la región Metropolitana.

```{r eval=TRUE, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, results='asis', fig.align = 'center'}

#Cargar paquetes
pacman::p_load(tidyverse,#universo de paquetes
               haven,# leer archivos stata
               stargazer,# tablas de regresión
              kableExtra)# Tablas fancy

#ahora con Kable, queda una tabla fancy

pc_region<- pc_region %>% select(-c("empresas", "trabajadores")) 

pc_region <- round(pc_region*100, 2)

kable(pc_region,
      caption = "Distribución de trabajadores y empresas por región, ENADEL 2023",
      col.names = c("Región","% Empresas", "% Trabajadores"),
      position = "center") %>% 
  kable_classic(full_width = F,
                html_font = "Century Gothic") %>% #Definimos fuente
  footnote(" ",#Especificamos la nota al pie
           general_title = "Fuente: Elaboración propia utilizando datos de ENADEL 2023, datos expandidos.")

```


### Contratados en los últimos 12 meses

##### Contrataciones por ocupación

##### Contrataciones por ocupación: Sector Construcción

##### Contrataciones por ocupación: Sector Agrícola

### Vacantes en los últimos 12 meses

##### Ocupaciones de difícil cobertura

##### Ocupaciones de Difícil Cobertura: Sector Construcción

##### Ocupaciones de Difícil Cobertura: Sector Agrícola

### Dificultades para la contratación

##### Dificultades para la contratación: Sector Construcción 

##### Dificultades para la contratación: Sector Agrícola

### Educación y experiencia

### Canales de reclutamiento

### Conocimiento de instituciones y programas

### Apéndice A: Ocupaciones de Difícil Cobertura


